package cryptoclient_test

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"os"
	"testing"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"

	haptov1 "github.com/chibuike-kt/hapto-api/gen/hapto/v1"
	"github.com/chibuike-kt/hapto-api/internal/cryptoclient"
)

// testCertsDir is the repo-root certs/ directory, generated by
// scripts/gen-certs.sh, reached relative to this package's directory
// (go test's working directory is always the package's source directory).
const testCertsDir = "../../../../certs"

func testTLSConfig() cryptoclient.TLSConfig {
	return cryptoclient.TLSConfig{
		CertFile: getEnvOr("HAPTO_CRYPTO_TLS_CERT", testCertsDir+"/hapto-api.crt"),
		KeyFile:  getEnvOr("HAPTO_CRYPTO_TLS_KEY", testCertsDir+"/hapto-api.key"),
		CAFile:   getEnvOr("HAPTO_CRYPTO_TLS_CA", testCertsDir+"/ca.crt"),
	}
}

func getEnvOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func testAddr() string {
	return getEnvOr("HAPTO_CRYPTO_ADDR", "localhost:50051")
}

// dialTestClient connects to a real hapto-crypto instance over mTLS. gRPC
// connects lazily, so Dial alone can't tell us whether the server is
// reachable; we ping it with a real call and skip the test if that fails —
// whether because hapto-crypto isn't running, or because certs haven't
// been generated yet (scripts/gen-certs.sh).
func dialTestClient(t *testing.T) *cryptoclient.Client {
	t.Helper()

	addr := testAddr()

	client, err := cryptoclient.Dial(addr, testTLSConfig())
	if err != nil {
		t.Skipf("hapto-crypto not available: %v", err)
	}
	t.Cleanup(func() {
		if err := client.Close(); err != nil {
			t.Logf("close crypto client: %v", err)
		}
	})

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	if _, _, err := client.ValidatePublicKey(ctx, make([]byte, 32), haptov1.SignatureAlgorithm_SIGNATURE_ALGORITHM_ED25519); err != nil {
		t.Skipf("hapto-crypto not reachable at %s: %v", addr, err)
	}

	return client
}

func TestValidatePublicKey_RejectsMalformedKey(t *testing.T) {
	client := dialTestClient(t)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	valid, reason, err := client.ValidatePublicKey(ctx, []byte("too-short"), haptov1.SignatureAlgorithm_SIGNATURE_ALGORITHM_ED25519)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if valid {
		t.Fatal("expected malformed key to be rejected")
	}
	if reason == "" {
		t.Error("expected a reason for rejection")
	}
}

// TestValidatePublicKey_AcceptsValidKey is the mTLS round trip: dialTestClient
// only succeeds at all if hapto-api's client certificate handshakes
// correctly against hapto-crypto's server certificate, both signed by the
// same local CA.
func TestValidatePublicKey_AcceptsValidKey(t *testing.T) {
	client := dialTestClient(t)

	pub, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate key: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	valid, reason, err := client.ValidatePublicKey(ctx, pub, haptov1.SignatureAlgorithm_SIGNATURE_ALGORITHM_ED25519)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !valid {
		t.Fatalf("expected valid ed25519 key to be accepted, got reason: %s", reason)
	}
}

// TestDial_RejectsConnectionWithoutClientCert proves hapto-crypto actually
// enforces mTLS rather than just offering it: a TLS connection that trusts
// the server's cert but presents no client certificate of its own must be
// refused, not silently downgraded to "server-auth only".
func TestDial_RejectsConnectionWithoutClientCert(t *testing.T) {
	// Confirms hapto-crypto is reachable at all (skips otherwise) before
	// asserting anything about how it handles a bad handshake.
	dialTestClient(t)

	tlsCfg := testTLSConfig()
	caPEM, err := os.ReadFile(tlsCfg.CAFile)
	if err != nil {
		t.Skipf("ca cert not available: %v", err)
	}
	caPool := x509.NewCertPool()
	if !caPool.AppendCertsFromPEM(caPEM) {
		t.Fatal("parse ca cert: no valid certificates found")
	}

	// Deliberately omits Certificates: this trusts the server but presents
	// no client identity, which is exactly what a plaintext-minded client
	// (or an attacker without a CA-signed cert) would attempt.
	creds := credentials.NewTLS(&tls.Config{
		RootCAs:    caPool,
		MinVersion: tls.VersionTLS12,
	})

	conn, err := grpc.NewClient(testAddr(), grpc.WithTransportCredentials(creds))
	if err != nil {
		t.Fatalf("new client: %v", err)
	}
	defer func() {
		if err := conn.Close(); err != nil {
			t.Logf("close conn: %v", err)
		}
	}()

	client := haptov1.NewCryptoServiceClient(conn)
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	_, err = client.ValidatePublicKey(ctx, &haptov1.ValidatePublicKeyRequest{
		PublicKey: make([]byte, 32),
		Algorithm: haptov1.SignatureAlgorithm_SIGNATURE_ALGORITHM_ED25519,
	})
	if err == nil {
		t.Fatal("expected the RPC to fail without a client certificate")
	}
}
